
// export const typeColors: Record<string, string> = {
//   normal: '#A8A77A',
//   fire: '#EE8130',
//   water: '#6390F0',
//   electric: '#F7D02C',
//   grass: '#7AC74C',
//   ice: '#96D9D6',
//   fighting: '#C22E28',
//   poison: '#A33EA1',
//   ground: '#E2BF65',
//   flying: '#A98FF3',
//   psychic: '#F95587',
//   bug: '#A6B91A',
//   rock: '#B6A136',
//   ghost: '#735797',
//   dragon: '#6F35FC',
//   dark: '#705746',
//   steel: '#B7B7CE',
//   fairy: '#D685AD',
// }

export const typeColors: Record<string, string> = {
  normal: 'bg-type-normal-blur',
  fire: 'bg-type-fire-blur',
  water: 'bg-type-water-blur',
  electric: 'bg-type-electric-blur',
  grass: 'bg-type-grass-blur',
  ice: 'bg-type-ice-blur',
  fighting: 'bg-type-fighting-blur',
  poison: 'bg-type-poison-blur',
  ground: 'bg-type-ground-blur',
  flying: 'bg-type-flying-blur',
  psychic: 'bg-type-psychic-blur',
  bug: 'bg-type-bug-blur',
  rock: 'bg-type-rock-blur',
  ghost: 'bg-type-ghost-blur',
  dragon: 'bg-type-dragon-blur',
  dark: 'bg-type-dark-blur',
  steel: 'bg-type-steel-blur',
  fairy: 'bg-type-fairy-blur',
}
